language: cpp

compiler:
  - gcc
  
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libprotobuf-dev libboost-all-dev libgtk-3-dev libgtest-dev libgtkmm-3.0-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
