language: cpp

compiler:
  - gcc
  
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libprotobuf-dev libboost-all-dev libgtk-3-dev libgtkmm-3.0-dev g++-4.8
  - sudo apt-get install -y libgtest-dev
  - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
